name: PR Agent
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  pr_agent_job:
    runs-on: ubuntu-24.04
    steps:
      - name: PR Agent action step
        uses: Codium-ai/pr-agent@v0.46.0
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}